show date in message listing, use readline for interactive operation

diff --git a/readmail b/readmail
--- a/readmail
+++ b/readmail
@@ -12,7 +12,7 @@
 # Licensed under the MIT license:
 # http://www.opensource.org/licenses/mit-license.php
 #
-# @version 1.3.0
+# @version 1.4.0
 #
 
 # Send request and read succeeding response
@@ -23,9 +23,21 @@ pop_request()
 	echo "$1" >&6
 	read RESPONSE <&6
 
-	[[ $RESPONSE == -ERR* ]] && return 1
+	[[ $RESPONSE == -ERR* ]] && {
+		echo "error:" ${RESPONSE#*-ERR}
+		return 1
+	}
 
 	return 0
+}
+
+# Logout and close connection to pop box
+pop_close()
+{
+	pop_request 'QUIT'
+
+	exec 6<&-
+	exec 6>&-
 }
 
 # Open connection to pop box and login
@@ -48,21 +60,12 @@ pop_open()
 	return 1
 }
 
-# Logout and close connection to pop box
-pop_close()
-{
-	pop_request 'QUIT'
-
-	exec 6<&-
-	exec 6>&-
-}
-
 # Decode quoted-printable-encoded stream
 decode_quoted_printable()
 {
 	local IFS= T= CODE= ENCODED=0
 
-	while read -r -n 1 -d $'\r' C
+	while read -r -n 1 -d $CR C
 	do
 		[ "$C" == '=' ] &&
 			ENCODED=2 &&
@@ -102,15 +105,66 @@ EOF
 	pop_close
 }
 
+# Echo trimmed value of given MIME header field
+header_value()
+{
+	echo ${RESPONSE#*:}
+}
+
+# Parse multipart header field
+parse_multipart_header_field()
+{
+	if [ ${RESPONSE:0:1} == $'\t' ]
+	then
+		RESPONSE=$LAST_MIME_HEADER':'$RESPONSE
+	else
+		LAST_MIME_HEADER=${RESPONSE%%:*}
+	fi
+
+	case "$RESPONSE" in
+		[Cc]ontent-[Tt]ype:*)
+			TYPE=$TYPE${TYPE:+ }`header_value`
+			;;
+		[Cc]ontent-[Tt]ransfer-[Ee]ncoding:*)
+			ENCODING=$ENCODING${ENCODING:+ }`header_value`
+			;;
+	esac
+}
+
+# Parse a MIME header field
+parse_header_field()
+{
+	case "$RESPONSE" in
+		.)
+			return 1
+			;;
+		[Ff][Rr][Oo][Mm]:*)
+			FROM=`header_value`
+			;;
+		[Tt][Oo]:*)
+			TO=`header_value`
+			;;
+		[Ss][Uu][Bb][Jj][Ee][Cc][Tt]:*)
+			SUBJECT=`header_value`
+			;;
+		[Dd][Aa][Tt][Ee]:*)
+			DATE=`header_value`
+			;;
+		[Cc]ontent-*)
+			parse_multipart_header_field
+			;;
+	esac
+}
+
 # List message(s)
 #
 # @param 1 - list of index numbers or "NEW" to list only new messages
 list_messages()
 {
-	local RESPONSE= ONLYNEW= MESSAGES=
+	local RESPONSE= NEW= MESSAGES=
 
 	if [ "$1" == 'NEW' ]; then
-		ONLYNEW=1
+		NEW=1
 	else
 		MESSAGES="$1"
 	fi
@@ -134,6 +188,9 @@ list_messages()
 		MAILS="$MAILS $N"
 		IDS[$N]="$ID"
 	done
+	
+	# remove last LF
+	read <&6
 
 	local MAILBOX=[]
 	touch "$CACHE"
@@ -144,45 +201,37 @@ list_messages()
 	for N in $MAILS
 	do
 		local RECORD="`grep "^${IDS[$N]}" "$CACHE"`"
-		local FROM= SUBJECT=
+		local FROM= TO= SUBJECT= DATE= ENCODING=
+		local D
 
 		if [ "$RECORD" ]; then
-			local TMP=${RECORD#*|}
-			TMP=${TMP#*|}
-			FROM=${TMP%%|*}
-			SUBJECT=${RECORD##*|}
+			IFS='|' read D D FROM SUBJECT DATE <<EOF
+$RECORD
+EOF
 
 			MAILBOX[$N]="$RECORD"
 		else
 			pop_request "TOP $N 0" || break
 
-			FROM=
-			SUBJECT=
-
 			while read -d $CR RESPONSE <&6
 			do
-				case "$RESPONSE" in
-					.)
-						break
-						;;
-					From:*|from:*|FROM:*)
-						FROM=`echo ${RESPONSE#*:}`
-						;;
-					Subject:*|subject:*|SUBJECT:*)
-						SUBJECT=`echo ${RESPONSE#*:}`
-						;;
-				esac
+				parse_header_field || break
 			done
 
-			MAILBOX[$N]="${IDS[$N]}|0|$FROM|$SUBJECT"
+			# remove last LF
+			read <&6
+
+			MAILBOX[$N]="${IDS[$N]}|0|$FROM|$SUBJECT|$DATE"
 		fi
 
-		# skip message if it is in the cache already and ONLYNEW is set
-		[ "$ONLYNEW" ] && [ "$RECORD" ] && continue
+		# skip message if it is in the cache already and NEW is set
+		[ "$NEW" ] && [ "$RECORD" ] && continue
 
-		printf "%4d: " $N
-		echo "${FROM:0:72}"
-		echo "      ${SUBJECT:0:72}"
+		printf "%4d: %s\n      %s\n      %s\n\n" \
+			$N \
+			"${FROM:0:72}" \
+			"$DATE" \
+			"${SUBJECT:0:72}"
 	done
 
 	pop_close
@@ -190,7 +239,7 @@ list_messages()
 	# remove cache to get rid of messages that are no longer available
 	[ "$MESSAGES" ] || rm "$CACHE"
 
-	for (( N=${#MAILBOX[*]}; $N; N-- ))
+	for (( N=${#MAILBOX[*]}; $N; --N ))
 	do
 		# when not rebuild, check for existence first
 		[ "$MESSAGES" ] &&
@@ -234,60 +283,44 @@ EOF
 	}
 
 	local FROM= TO= SUBJECT= DATE= ENCODING= BODY=
-	local INHEADER=true IFS=$LF
+	local HEADER=true
 
 	while read -d $CR RESPONSE <&6
 	do
 		[[ $RESPONSE == . ]] && break
 
-		[ "$RESPONSE" ] || INHEADER=
+		[ "$RESPONSE" ] || HEADER=
 
-		if [ "$INHEADER" ]
+		if [ "$HEADER" ]
 		then
-			case "$RESPONSE" in
-				From:*|from:*|FROM:*)
-					FROM=`echo ${RESPONSE#*:}`
-					;;
-				To:*|to:*|TO:*)
-					TO=`echo ${RESPONSE#*:}`
-					;;
-				Subject:*|subject:*|SUBJECT:*)
-					SUBJECT=`echo ${RESPONSE#*:}`
-					;;
-				Date:*|date:*|DATE:*)
-					DATE=`echo ${RESPONSE#*:}`
-					;;
-				Content-transfer-encoding:*|\
-				Content-Transfer-Encoding:*|\
-				content-transfer-encoding:*)
-					ENCODING="${RESPONSE#*:}"
-					;;
-			esac
+			parse_header_field
 		else
 			BODY=$BODY$RESPONSE$LF
 		fi
 	done
 
+	# remove last LF
+	read <&6
+
 	# mark message as read
 	if ! [ -f "$CACHE" ] ||
 		! grep "^$ID|" "$CACHE" &> /dev/null; then
-		echo "$ID|1|$FROM|$SUBJECT" >> "$CACHE"
+		echo "$ID|1|$FROM|$SUBJECT|$DATE" >> "$CACHE"
 	else
-	# use sub shell to have IFS reset only in this context
 	(
 		local CACHECONTENT=`< $CACHE`
-		local IFS='|'
 		local MID READ
+		local FROM TO SUBJECT DATE ENCODING BODY
 
 		rm "$CACHE"
 
-		while read MID READ FROM SUBJECT
+		while IFS='|' read MID READ FROM SUBJECT DATE
 		do
 			[ $MID == $ID ] &&
 				READ=1
 
-			echo "$MID|$READ|$FROM|$SUBJECT" >> "$CACHE"
-		done << EOF
+			echo "$MID|$READ|$FROM|$SUBJECT|$DATE" >> "$CACHE"
+		done <<EOF
 $CACHECONTENT
 EOF
 	)
@@ -298,7 +331,7 @@ EOF
 	[[ $ENCODING == *quoted-printable* ]] &&
 		BODY=`echo $BODY | decode_quoted_printable`
 
-	less << EOF
+	less <<EOF
 `printf "%-8s: %s\n" "From" "$FROM"`
 `printf "%-8s: %s\n" "To" "$TO"`
 `printf "%-8s: %s\n" "Subject" "$SUBJECT"`
@@ -341,6 +374,9 @@ read_next_message()
 			NEXT=$N
 	done
 
+	# remove last LF
+	read <&6
+
 	pop_close
 
 	(( $NEXT )) &&
@@ -373,6 +409,9 @@ new_messages()
 		fi
 	done
 
+	# remove last LF
+	read <&6
+
 	pop_close
 }
 
@@ -391,29 +430,26 @@ file_message()
 		return
 	}
 
-	local DATE=`date +%Y%m%d%H%M%S`
-	local FILE="unknown-$DATE"
-	local FROM=
-	local INHEADER=true
-	local IFS=$LF
+	local FILE="${BIN}-message"
+	local FROM= TO= SUBJECT= DATE= ENCODING=
+	local HEADER=true
 
-	while read -d $CR RESPONSE <&6
+	while IFS=$LF read -d $CR RESPONSE <&6
 	do
 		[[ $RESPONSE == . ]] && break
 
-		[ "$RESPONSE" ] || INHEADER=
+		[ "$RESPONSE" ] || HEADER=
 
-		[ "$INHEADER" ] &&
-			case "$RESPONSE" in
-				From:*|from:*|FROM:*)
-					FROM="${RESPONSE#*:}"
-					;;
-			esac
+		[ "$HEADER" ] &&
+			parse_header_field
 
 		echo "$RESPONSE" >> "$FILE"
 	done
 
 	pop_close
+
+	[ "$DATE" ] ||
+		DATE=`date +%Y%m%d%H%M%S`
 
 	FROM=${FROM#*<}
 	FROM=`echo ${FROM%>*}`
@@ -591,9 +627,21 @@ smtp_request()
 		[ "${RESPONSE:3:1}" != "-" ] && break
 	done
 
-	[[ $RESPONSE == [23]* ]] || return 1
+	[[ $RESPONSE == [23]* ]] || {
+		echo "error: $RESPONSE"
+		return 1
+	}
 
 	return 0
+}
+
+# Close connection to smtp server and log off
+smtp_close()
+{
+	smtp_request 'QUIT'
+
+	exec 7<&-
+	exec 7>&-
 }
 
 # Open connection to smtp server and log on
@@ -618,15 +666,6 @@ smtp_open()
 	smtp_close
 
 	return 1
-}
-
-# Close connection to smtp server and log off
-smtp_close()
-{
-	smtp_request 'QUIT'
-
-	exec 7<&-
-	exec 7>&-
 }
 
 # Write and send a message
@@ -708,27 +747,15 @@ answer_message()
 		return
 	}
 
-	local FROM=
-	local SUBJECT=
-	local INHEADER=true
-	local IFS=$LF
+	local FROM= TO= SUBJECT= DATE= ENCODING=
 
 	while read -d $CR RESPONSE <&6
 	do
-		[[ $RESPONSE == . ]] && break
-
-		[ "$RESPONSE" ] || INHEADER=
-
-		[ "$INHEADER" ] &&
-			case "$RESPONSE" in
-				From:*|from:*|FROM:*)
-					FROM=`echo ${RESPONSE#*:}`
-					;;
-				Subject:*|subject:*|SUBJECT:*)
-					SUBJECT=`echo ${RESPONSE#*:}`
-					;;
-			esac
+		parse_header_field || break
 	done
+
+	# remove last LF
+	read <&6
 
 	pop_close
 
@@ -749,7 +776,7 @@ config_prompt()
 	local ANSWER= PRESET= DEFAULT=
 
 	eval "DEFAULT=\$$1"
-	
+
 	[ "$DEFAULT" ] && PRESET=" [$DEFAULT]"
 	[ "$OPTIONAL" ] && PRESET="$PRESET (optional)"
 
@@ -792,17 +819,17 @@ config_check()
 	}
 
 	if [ -f "$CONFIG" ]; then
-		cat << EOF
+		cat <<EOF
 Missing settings in $CONFIG!
 Do you like to change/complete your configuration now ([yes]/no)
 EOF
 	else
-		cat << EOF
+		cat <<EOF
 Missing configuration file! This seems to be the first time you are running
 this script. Do you like to set up a configuration now? ([yes]/no)
 EOF
 	fi
-	
+
 	local ANSWER
 	read -e ANSWER
 
@@ -877,6 +904,15 @@ validate_indices()
 		INDICES="`echo "$INDICES" | sort -nr`"
 }
 
+# Quit background instance
+quit_background()
+{
+	[ -f "$PIDFILE" ] || return
+
+	kill `< "$PIDFILE"` &> /dev/null
+	rm -f "$PIDFILE"
+}
+
 # Run given command
 #
 # @param 1 - some command
@@ -885,7 +921,7 @@ run()
 {
 	case "$1" in
 		h*|\?*)
-			cat << EOF
+			cat <<EOF
   p(eek)                 peek for new messages
   P(eek)                 peek continuously & notify on mail
   s(tatus)               request mailbox status
@@ -919,21 +955,20 @@ EOF
 				return
 			fi
 
-			[ -f "$PIDFILE" ] &&
-				kill `< $PIDFILE` &> /dev/null
+			quit_background
 
 			while true
 			do
 				# this will NOT mark messages as listed, so you need to call
 				# "readmail l q" in your notification if you're using this
-				# script just to be notified, this wouldn't really be a peek
-				# because it changes the cache
+				# script just to be notified, otherwise this wouldn't really
+				# be a "peek" because it changes the cache
 				new_messages || break
 
 				# allow a list of commands to be executed
 				(( NEW_MAILS > 0 )) &&
-					/bin/bash << EOF
-#!/bin/bash
+					/usr/bin/env bash <<EOF
+#!/usr/bin/env bash
 $NOTIFICATION
 EOF
 
@@ -1017,6 +1052,7 @@ EOF
 		a*)
 			(( $# < 2 )) && return
 
+			shift
 			answer_message $1
 			;;
 		w*)
@@ -1030,11 +1066,7 @@ EOF
 			exit
 			;;
 		Q*)
-			[ -f "$PIDFILE" ] && {
-				kill `< $PIDFILE` &> /dev/null
-				rm "$PIDFILE"
-			}
-
+			quit_background
 			exit
 			;;
 		*)
@@ -1048,10 +1080,10 @@ EOF
 	esac
 }
 
-readonly BASENAME=${0##*/}
-readonly CONFIG="$HOME/.${BASENAME}rc"
-readonly CACHE="$HOME/.${BASENAME}cache"
-readonly PIDFILE="$HOME/.${BASENAME}pid"
+readonly BIN=${0##*/}
+readonly CONFIG="$HOME/.${BIN}rc"
+readonly CACHE="$HOME/.${BIN}cache"
+readonly PIDFILE="$HOME/.${BIN}pid"
 readonly CR=$'\r'
 readonly LF=$'\n'
 
@@ -1072,10 +1104,7 @@ do
 done
 
 # interactive operation
-while true
+while read -p "$POP_ACCOUNT> " -e CMD
 do
-	printf "$POP_ACCOUNT> "
-	read -e CMD
-
 	run $CMD
 done
